version: "3"

services:
  app:
    build: ./docker
    container_name: app
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    networks:
      app:
        ipv4_address: 172.28.1.1
        aliases:
          - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app
    networks:
      app:
        ipv4_address: 172.28.1.2
        aliases:
          - nginx

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
