version: "3"

services:
  app:
    build: ./docker
    container_name: app
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app
